import { useState, useEffect } from "react";
import Eeveelution_info from "./Eeveelution_info";
import "./scss/Eeveelution.css"; 

const Eeveelution = () => {
    const [EeveelutionList, setEeveelutionList] = useState(null);
    const [EeveelutionImages, setEeveelutionImages] = useState([
        {   
            "pokemon_name": "Eevee",
            "image_src": "./images/eevee.jpg",
            "info": <div className="paragraph">
                         <p>Eevee is a mammalian, quadrupedal Pokémon with primarily brown fur. The tip of its bushy tail and its large furry collar are cream-colored. It has short, slender legs with three small toes and a pink paw pad on each foot. Eevee has brown eyes, long pointed ears with dark brown interiors, and a small black nose.</p>
                         <p>Eevee is rarely found in the wild and is mostly only found in cities and towns. However, it is said to have an irregularly shaped genetic structure that is easily influenced by its environment. This allows it to adapt to a variety of habitats by evolving</p>
                    </div>
        },
        {
            "pokemon_name": "Espeon",
            "image_src": "./images/Espeon.jpg",
            "info": <div className="paragraph">
                <p>Espeon is a quadrupedal, mammalian Pokémon with slender legs and dainty paws. It is covered in fine, lilac fur. Its ears are large, and it has purple eyes with white pupils. There are tufts of fur near its eyes, and a small, red gem embedded in its forehead. It also has a thin, forked tail.</p>
                <p>Espeon's velvety fur is so sensitive that it can sense minuscule shifts in the air, allowing it to predict the weather and its enemies' movements. When predicting an opponent's actions, the tip of its tail quivers.</p>
                <p>The gem on Espeon's forehead glows when it unleashes psychic energy from the gem and darkens when all of the built-up energy has been exhausted. Espeon builds up its psychic power by bathing in the sunlight. As such, it does not handle battles at night well.</p>
                <p>Espeon shows extreme loyalty to any Trainer that it considers worthy, even being said to have awakened its psychic powers from its desire to protect its Trainer; others say that its powers were born from its need to keep itself safe</p>
            </div>
        },
        {
            "pokemon_name": "Flareon",
            "image_src": "./images/Flareon.jpg",
            "info": <div className="paragraph">
                <p>Flareon is a mammalian, quadrupedal Pokémon covered in short, reddish-orange fur. It has long ears with black interiors, dark eyes, and a small black nose. There are three small toes and a yellow paw pad on each foot. Fluffy yellow fur forms a small tuft on its head, as well as its bushy tail and a mane around its chest and neck. It will fluff out its collar to cool down its high body temperature. This high temperature is caused by its internal flame sac. Flareon stores and heats inhaled air in this sac and then exhales it as fire. It is an omnivore that roasts either Berries or prey before consumption.</p>
            </div>
        },
        {
            "pokemon_name": "Jolteon",
            "image_src": "./images/Jolteon.png",
            "info": <div className="paragraph">
                <p>Jolteon is a quadrupedal, mammalian Pokémon. It is covered in yellow fur with a spiky fringe around its tail and a white ruff around its neck. Its ears are large and pointed with black interiors, and its eyes and small nose are black. It has slender legs and small paws, each with three toes and a pink paw-pad. /nJolteon's prickly fur is made of electrically charged needles and generates negatively charged ions, which create a sparking noise as it moves. It also has an electricity-generating organ in its lungs. The static electricity in its fur amplifies the low-level electricity generated by its cells and allow it to discharge 10,000-volt lightning bolts.</p>
            </div> 
         },
        {
            "pokemon_name": "Leafeon",
            "image_src": "./images/Leafeon.png",
            "info": <div className="paragraph">
                <p>Leafeon is a mammalian, quadrupedal Pokémon. Its body is tan with dark brown paws. It has a multitude of small green sprouts growing all over its legs, chest, and back, with the longest one on its head, in front of four tan tufts of fur. Leafeon's ears and tail are stylized to resemble tattered leaves. It has brown eyes and a small, brown nose. This Pokémon's cellular structure is similar to plants, which allows it to perform photosynthesis and purify the air around it by sleeping under the sunlight; it gets its energy in this way instead of eating. It is a pacifistic, quiet Pokémon, preferring not to fight, though sharpens its leafy tail for the occasions it needs to. Its aroma is similar to fresh grass in its youth; as it ages, this fragrance bears more of a resemblance to fallen leaves. The aroma is favored in Galar, where it is used to create a popular perfume.</p>
            </div> 
        },
        {
            "pokemon_name": "Sylveon",
            "image_src": "./images/Sylveon.png",
            "info": <div className="paragraph">
                <p>Sylveon is a quadrupedal, mammalian Pokémon covered with pale cream-colored fur with pink feet, ears, and tail. It has light blue eyes, long ears with blue interiors and thicker fur, a tiny nose, and two stray tufts of fur on top of its head. There are two bows on its body: one at the base of its left ear and one at its neck. Each bow is pale cream with a pink center and trails a pair of ribbon-like feelers. The feelers are pale cream with light blue tips. Before the tip of each feeler is a pink and then a dark blue stripe. It has slender legs with small, three-toed paws and a fluffy, slightly curved tail. Sylveon's ribbon-like feelers emit a soothing aura that erases any sense of hostility, enabling it to stop fights. When hunting, it swirls its feelers as a distraction while the aura weakens feelings of hostility in its prey, then pounces on the victim. It will also wrap its feelers around its Trainer's arm as they walk together, which allows it to read their feelings.</p>
            </div> 
        },
        {
            "pokemon_name": "Glaceon",
            "image_src": "./images/Glaceon.jpg",
            "info": <div className="paragraph">
                <p>Glaceon is a quadrupedal, mammalian Pokémon covered in light-blue fur that can be frozen into sharp quills. It has long, pointed ears, dark eyes, and a small nose. A teal crest with two dangling flaps adorns its head, resembling hair or headgear. Glaceon has two dark blue, rhombus-shaped markings on its back; the tip of its tail, feet, and flaps are the same shade of blue. By controlling its body temperature, the moisture in the air freezes, producing ice crystals surrounding it. It is capable of freezing its fur into sharp needle-like icicles, used to tackle its prey. It can drop its body temperature below -75 degrees Fahrenheit. Those captivated by Glaceon's beautiful snowfall will be instantly frozen without realizing it. Glaceon is rather popular in ski resorts due to its ability to create powdery snow.</p>
            </div> 
        },
        {
            "pokemon_name": "Umbreon",
            "image_src": "./images/Umbreon.jpg",
            "info": <div className="paragraph">
                <p>Umbreon is a Pokémon which has a sleek, black body with four slender legs and crimson eyes. It has two pairs of pointed teeth (one in the upper jaw and one in the lower jaw) which are visible when its mouth is open. It has long, pointed ears and a bushy tail, each with a yellow band around them. Its forehead and legs have yellow rings on them. Umbreon's yellow markings glow at night or when it is excited, striking fear into anyone nearby. Upon being exposed to the moonlight, the rings on its body glow, filling it with a mysterious energy. Umbreon is nocturnal and as such, it has powerful night vision. Its black fur helps it hide in the darkness of night while waiting for its prey. When it spots the target, its rings gain a dim yet ominous glow, and it lunges for the prey's throat before eating it. Its yellow rings glow when it leaps to attack. Whenever Umbreon gets angry, it secretes and sprays poisonous sweat into the offender's eyes. Eevee evolved into this form due to exposure to the moonlight altering its genetic structure.</p>
            </div> 
        },
        {
            "pokemon_name": "Vaporeon",
            "image_src": "./images/Vaporeon.png",
            "info": <div className="paragraph">
                <p>Vaporeon is a Pokémon that shares physical traits with both aquatic and land animals. Vaporeon's body is light blue with a dark blue marking around its head and a spiky ridge down its spine. It has black eyes and a tiny black nose. There a white fin encircling its neck and three fins with cream-colored webbing on its head. One of these fins is on each side of its head similar to ears and one is directly on top of its head similar in appearance to a dorsal fin. Vaporeon is a quadruped with three small toes on each foot and dark blue paw pads on the hind feet. Its split tail fin has been mistaken for a mermaid's in the past. It can detect moisture with its fins, which vibrate when rain will fall soon.</p>
            </div> 
        }
    ]);

    useEffect(() => {
        const toReturn = EeveelutionImages.map((item)=>{
            return <Eeveelution_info PokemonName={item.pokemon_name} Image_src={item.image_src} Paragraph={item.info}/> 
        })
        setEeveelutionList(toReturn)
    }, []);
    

    return ( 
        <div className="Eeveelution">
            <div className="Eeveelution__main">
                <div className="Title">
                    <h1>Eeveelution</h1>
                </div>
                <div className="container sources">
                    <p>This infomration is gathered from Bulbapedia, the community-driven Pokémon encyclopedia. Give them major respect and visit their site for more in dept overview :)</p>
                </div>
                <div className="container Eeveelution_information">
                    <div className="general_information">
                        <p> <i>An Eeveelution</i> is a term used for the current group of eight Pokémon that evolve from Eevee. It is a portmanteau of the words "Eevee" and "evolution" - Its definition may be extended to include Eevee itself.<br/>It originally was an unofficial term used by fans, but the term eventually passed into the realm of official usage first as a pun in the official guide of Pokémon Stadium 2and then later in the TCG Theme Deck Eeveelution, as well as in the game Pokémon Ranger: Shadows of Almia.</p>
                        <br/><p>In Generation I, Eevee is obtained at the Celadon Mansion and can evolve into Jolteon, Flareon, or Vaporeon through the use of an Evolution stone.</p>
                        
                        <br/><p>Eevee is again available relatively early in <i>Generation II</i>, which introduces two new Eeveelutions: Espeon and Umbreon, obtained when Eevee is leveled up with high friendship at certain times of the day. Each of Ecruteak City's Kimono Girls owns one of the five Eeveelutions that existed in <i>Generation II</i>. Because there is no clock system in FireRed and LeafGreen, Eevee cannot evolve into Espeon or Umbreon even though they exist and can be traded in from Ruby, Sapphire, and Emerald Versions. </p>
                        
                        <br/><p>Though no new Eeveelutions were introduced in <i>Generation III</i>, <i>Generation IV</i> added another pair of new Eeveelutions, Leafeon and Glaceon, which are obtained by leveling Eevee up in certain areas, another departure from the methods of evolution in previous generations. Because there is no Moss Rock or Icy Rock in HeartGold and SoulSilver, Eevee cannot evolve into Leafeon or Glaceon even though they exist and can be traded in from Diamond, Pearl, and Platinum Versions. </p>
                        
                        <br/><p>Eeveelutions once again skip a generation and introduce a new evolution in <i>Generation VI</i>: Sylveon. </p>
                    
                        <div className="evelutions">
                            <ul>
                                {EeveelutionList}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
     );
}
 
export default Eeveelution;